preload = /home/ss/wallpapers/1.png
preload = /home/ss/wallpapers/2.png
preload = /home/ss/wallpapers/3.png
preload = /home/ss/wallpapers/4.png
preload = /home/ss/wallpapers/5.png
preload = /home/ss/wallpapers/6.png
preload = /home/ss/wallpapers/ADAPT_OR_DIE.png
preload = /home/ss/wallpapers/jjk-godlike.png
